---
- name: Deploy GitLab servers
  hosts: gitlab-servers
  remote_user: root
  become: true
  roles:
  - gbraad.gitlab-server

- name: Deploy GitLab runners
  hosts: gitlab-runners
  remote_user: root
  become: true
  roles:
  - gbraad.gitlab-cirunner
