---
  - name: Install list of required packages
    package: name={{ item }} state=installed
    become: yes
    become_method: sudo
    with_items:
    - docker
  
  - name: Enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - docker
  
  - name: Add GitLab CI multi runner repository
    yum_repository:
      name: runner_gitlab-ci-multi-runner
      description: GitLab CI multi runner
      file: runner_gitlab-ci-multi-runner
      baseurl: https://packages.gitlab.com/runner/gitlab-ci-multi-runner/el/7/$basearch
      gpgcheck: no
  
  - name: Add GitLab CI multi runner source repository
    yum_repository:
      name: runner_gitlab-ci-multi-runner-source
      description: GitLab CI multi runner source
      file: runner_gitlab-ci-multi-runner
      baseurl: https://packages.gitlab.com/runner/gitlab-ci-multi-runner/el/7/SRPMS
      gpgcheck: no
  
  - name: Install GitLab CI multi runner
    package: name=gitlab-ci-multi-runner state=installed
